apiVersion: apps/v1
kind: Deployment
metadata:
  name: kdaudit-operator
  namespace: kdaudit
  labels:
    app: kdaudit-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kdaudit-operator
  template:
    metadata:
      labels:
        app: kdaudit-operator
    spec:
      serviceAccount: kdaudit-operator
      containers:
        - name: kdaudit
          image: local/kdaudit-operator
          imagePullPolicy: Never
